export const MATCHES = [
  {
    id: 1,
    homeTeam: "Zimbabwe",
    awayTeam: "Namibia",
    homeScore: null,
    awayScore: null,
    date: "2025-06-14",
    time: "15:00",
    venue: "Harare Sports Club",
    competition: "Rugby Africa Cup",
    status: "upcoming",
    homeLogo: "/flags/zim.svg",
    awayLogo: "/flags/nam.svg",
  },
  {
    id: 2,
    homeTeam: "Kenya",
    awayTeam: "Zimbabwe",
    homeScore: 22,
    awayScore: 27,
    date: "2025-03-08",
    time: "14:00",
    venue: "RFUEA Ground, Nairobi",
    competition: "Rugby Africa Cup",
    status: "result",
    homeLogo: "/flags/ken.svg",
    awayLogo: "/flags/zim.svg",
  },
  {
    id: 3,
    homeTeam: "Zimbabwe",
    awayTeam: "Uganda",
    homeScore: 31,
    awayScore: 18,
    date: "2025-02-22",
    time: "15:00",
    venue: "Harare Sports Club",
    competition: "Rugby Africa Cup",
    status: "result",
    homeLogo: "/flags/zim.svg",
    awayLogo: "/flags/uga.svg",
  },
  {
    id: 4,
    homeTeam: "Zimbabwe",
    awayTeam: "Senegal",
    homeScore: null,
    awayScore: null,
    date: "2025-07-05",
    time: "16:00",
    venue: "Harare Sports Club",
    competition: "Rugby Africa Cup",
    status: "upcoming",
    homeLogo: "/flags/zim.svg",
    awayLogo: "/flags/sen.svg",
  },
];

export const NEWS = [
  {
    id: 1,
    title: "Sables Named for Rugby Africa Cup Qualifier",
    excerpt: "Head coach Brendan Dawson has named a 35-man squad for the upcoming Rugby Africa Cup qualifier against Namibia.",
    date: "2025-03-12",
    category: "Squad News",
    image: "/news/sables-squad.jpg",
    slug: "sables-named-rwa-cup-qualifier",
  },
  {
    id: 2,
    title: "ZRU Launches National Youth Development Program",
    excerpt: "The Zimbabwe Rugby Union officially launches a nationwide grassroots development programme targeting under-14 players.",
    date: "2025-03-05",
    category: "Development",
    image: "/news/youth-program.jpg",
    slug: "zru-youth-development-program",
  },
  {
    id: 3,
    title: "Sables Claim Stunning Victory Over Kenya",
    excerpt: "Zimbabwe's national team delivered a masterclass performance to defeat Kenya 27-22 in Nairobi, keeping their Rugby Africa Cup hopes alive.",
    date: "2025-03-08",
    category: "Match Report",
    image: "/news/kenya-win.jpg",
    slug: "sables-victory-kenya",
  },
  {
    id: 4,
    title: "New Sponsor Partnership Announced",
    excerpt: "ZRU is proud to welcome a new official sponsor as part of the union's ambitious five-year growth strategy.",
    date: "2025-02-28",
    category: "Partnership",
    image: "/news/sponsor.jpg",
    slug: "new-sponsor-partnership",
  },
];

export const PLAYERS = [
  {
    id: 1,
    name: "Brendan Munyai",
    position: "Fly-half",
    caps: 34,
    points: 187,
    age: 27,
    club: "Old Hararians",
    image: "/players/player1.jpg",
    number: 10,
  },
  {
    id: 2,
    name: "Tapiwa Tsomondo",
    position: "Prop",
    caps: 28,
    points: 15,
    age: 29,
    club: "Harare Sports Club",
    image: "/players/player2.jpg",
    number: 3,
  },
  {
    id: 3,
    name: "Cleopas Kundiona",
    position: "Wing",
    caps: 41,
    points: 110,
    age: 26,
    club: "Old Hararians",
    image: "/players/player3.jpg",
    number: 14,
  },
  {
    id: 4,
    name: "Victor Mhiribidi",
    position: "Lock",
    caps: 19,
    points: 10,
    age: 24,
    club: "Harare Sports Club",
    image: "/players/player4.jpg",
    number: 5,
  },
  {
    id: 5,
    name: "Dion Khumalo",
    position: "Scrum-half",
    caps: 23,
    points: 45,
    age: 25,
    club: "Matabeleland Tuskers",
    image: "/players/player5.jpg",
    number: 9,
  },
  {
    id: 6,
    name: "Prince Tawonezvi",
    position: "Number 8",
    caps: 37,
    points: 55,
    age: 28,
    club: "Old Hararians",
    image: "/players/player6.jpg",
    number: 8,
  },
];

export const ARTICLES = [
  {
    id: 1,
    title: "ZRU Annual Report 2024",
    description: "Full annual report covering financials, governance, player development and match statistics for the 2024 season.",
    date: "2025-01-15",
    category: "Annual Report",
    fileSize: "4.2 MB",
    pages: 48,
    thumbnail: "/pdfs/annual-report-2024.jpg",
    file: "/pdfs/annual-report-2024.pdf",
  },
  {
    id: 2,
    title: "Rugby Africa Cup 2025 Preview",
    description: "In-depth analysis of Zimbabwe's Rugby Africa Cup 2025 campaign, fixtures, and squad profiles.",
    date: "2025-02-20",
    category: "Tournament Guide",
    fileSize: "2.1 MB",
    pages: 24,
    thumbnail: "/pdfs/rac-2025-preview.jpg",
    file: "/pdfs/rac-2025-preview.pdf",
  },
  {
    id: 3,
    title: "Sables Coaching Manual — Grassroots Edition",
    description: "Official coaching guide for community coaches developing young players at the grassroots level.",
    date: "2024-11-10",
    category: "Development",
    fileSize: "6.8 MB",
    pages: 72,
    thumbnail: "/pdfs/coaching-manual.jpg",
    file: "/pdfs/coaching-manual.pdf",
  },
  {
    id: 4,
    title: "ZRU Integrity & Disciplinary Policy 2025",
    description: "Updated integrity and disciplinary framework governing all players, coaches, and officials under ZRU jurisdiction.",
    date: "2025-01-01",
    category: "Governance",
    fileSize: "1.3 MB",
    pages: 18,
    thumbnail: "/pdfs/integrity-policy.jpg",
    file: "/pdfs/integrity-policy.pdf",
  },
];

export const TICKER_ITEMS = [
  { id: 1, text: "RESULT: Zimbabwe 31-18 Uganda | Rugby Africa Cup" },
  { id: 2, text: "RESULT: Kenya 22-27 Zimbabwe | Rugby Africa Cup" },
  { id: 3, text: "UPCOMING: Zimbabwe vs Namibia | Jun 14, 15:00 | Harare Sports Club" },
  { id: 4, text: "SQUAD ANNOUNCED: 35-man squad named for Rugby Africa Cup qualifiers" },
  { id: 5, text: "UPCOMING: Zimbabwe vs Senegal | Jul 5, 16:00 | Harare Sports Club" },
];

// RWC 2027 target date
export const RWC_DATE = new Date("2027-10-08T00:00:00");
